[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.76"
chrono = "0.4.31"
map-macro = "0.2.6"
octocrab = "0.32.0"
semver = "1.0.20"
serde = "1.0.193"
serde_json = "1.0.108"
tracing = "0.1.40"
url = "2.5.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.4.11"
features = ["derive"]

[dependencies.tokio]
version = "1.35.1"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]
