[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
map-macro = "0.2.6"
octocrab = "0.32.0"
semver = "1.0.20"
serde = "1.0.193"
serde_json = "1.0.108"
url = "2.5.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.4.10"
features = ["derive"]

[dependencies.tokio]
version = "1.34.0"
features = ["full"]
